-- Source: data inventaris blum fix (1).xlsx
-- Covers 590 records in Rak A, B, C, D, E, F, G, H, J, K, T, and U.
-- Some spreadsheet item numbers repeat within a rack; later entries receive a numeric suffix in code.

with inventory_seed (rack_code, code, name, item_type, initial_quantity, used_quantity, added_quantity, current_quantity, source_note, source_row) as (
  values
    ('A', 'RA-A-001', 'Double Foam Tape', 'consumable', 4, null, null, 4, 'Consumable', 4),
    ('A', 'RA-A-002', 'Masking Tape', 'consumable', 3, null, null, 3, 'Consumable', 5),
    ('A', 'RA-A-003', 'Machi Tape', 'consumable', null, null, null, null, 'Consumable', 6),
    ('A', 'RA-A-004', 'Double Tape Putih', 'consumable', 1, null, null, 1, 'Consumable', 7),
    ('A', 'RA-A-005', 'Lakban Kuning', 'consumable', null, null, null, null, 'Consumable', 8),
    ('A', 'RA-A-006', 'Lakban Putih', 'consumable', 2, null, 1, 3, 'Consumable', 9),
    ('A', 'RA-A-007', 'Solasi Tahan Panas (Lakban PTFE)', 'consumable', 3, null, null, 3, 'Consumable', 10),
    ('A', 'RA-A-008', 'Refill Tinta Biru', 'consumable', 3, null, null, 3, 'Consumable', 11),
    ('A', 'RA-A-009', 'Refill Tinta Merah', 'consumable', 3, null, null, 3, 'Consumable', 12),
    ('A', 'RA-A-010', 'Refill Tinta Hitam', 'consumable', 1, null, null, 1, 'Consumable', 13),
    ('A', 'RA-A-011', 'Kaca Las', 'consumable', 1, null, null, 1, 'Consumable', 14),
    ('A', 'RA-A-012', 'Lem pipa PVC', 'consumable', null, null, null, null, 'Consumable', 15),
    ('A', 'RA-A-013', 'Lem G', 'consumable', 2, null, null, 2, 'Consumable', 16),
    ('A', 'RA-A-014', 'Solasi Bakar', 'consumable', 2, null, null, 2, 'Consumable', 17),
    ('A', 'RA-A-015', 'Perekat UHU', 'consumable', null, null, null, null, 'Consumable', 18),
    ('A', 'RA-A-016', 'Seal Tape', 'consumable', 3, null, null, 3, 'Consumable', 19),
    ('A', 'RA-A-017', 'Lem Alteko', 'consumable', null, null, null, null, 'Consumable', 20),
    ('A', 'RA-A-018', 'Amplas', 'consumable', 1, null, null, 1, 'Consumable', 21),
    ('A', 'RA-A-019', 'Push Pin', 'consumable', 1, null, null, 1, 'Consumable', 22),
    ('A', 'RA-A-020', 'Solasi Listrik', 'consumable', 1, null, null, 1, 'Consumable', 23),
    ('A', 'RA-A-021', 'Spidol Paint', 'consumable', 3, null, null, 3, 'Consumable', 24),
    ('A', 'RA-A-022', 'Spidol Artline', 'consumable', 3, null, null, 3, 'Consumable', 25),
    ('A', 'RA-A-023', 'Staples', 'consumable', 1, null, null, 1, 'Consumable', 26),
    ('A', 'RA-A-024', 'Isi Staples', 'consumable', 2, null, null, 2, 'Consumable', 27),
    ('A', 'RA-A-025', 'Clip Blinder', 'consumable', 2, null, null, 2, 'Consumable', 28),
    ('A', 'RA-A-026', 'Bulpoin', 'consumable', 3, null, null, 3, 'Consumable', 29),
    ('A', 'RA-A-027', 'Tespen Sensor', 'inventory', 1, null, null, 1, 'Inventory', 30),
    ('A', 'RA-A-028', 'Sensor Ultrasonik', 'consumable', 2, null, null, 2, 'Consumable', 31),
    ('A', 'RA-A-029', 'Penanda Kunci', 'consumable', 2, null, null, 2, 'Consumable', 32),
    ('A', 'RA-A-030', 'Timah', 'consumable', 5, null, null, 5, 'Consumable', 33),
    ('A', 'RA-A-031', 'Fluks', 'consumable', 2, null, null, 2, 'Consumable', 34),
    ('A', 'RA-A-032', 'Foam Tape', 'consumable', 1, null, null, 1, 'Consumable', 35),
    ('A', 'RA-A-033', 'Cutter', 'inventory', 4, null, null, 4, 'Inventory', 36),
    ('A', 'RA-A-034', 'Isi Cutter', 'consumable', 8, null, null, 8, 'Consumable', 37),
    ('A', 'RA-A-035', 'PU Foam Spray', 'consumable', 3, 3, null, null, 'Consumable', 38),
    ('A', 'RA-A-036', 'Pelindung Kepala', 'consumable', 1, null, null, 1, 'Consumable', 39),
    ('A', 'RA-A-037', 'Masker', 'consumable', 2, null, null, 2, 'Consumable', 40),
    ('A', 'RA-A-038', 'Ribbon Tube TR-100BK', 'consumable', 3, null, null, 3, 'Consumable', 41),
    ('A', 'RA-A-039', 'Ribbon Tube TZC-241 8M', 'consumable', 6, null, null, 6, 'Consumable', 42),
    ('A', 'RA-A-040', 'ESP32 WROOM 32D', 'consumable', 1, null, null, 1, 'Consumable', 43),
    ('A', 'RA-A-041', 'Limit Switch', 'consumable', null, null, null, null, 'Consumable', 44),
    ('A', 'RA-A-042', 'Sensor PIR', 'consumable', null, null, null, null, 'Consumable', 45),
    ('A', 'RA-A-043', 'Reflektor Omron E39-R1', 'consumable', null, null, null, null, 'Consumable', 46),
    ('A', 'RA-A-044', 'Spidol papan tulis merah', 'consumable', 2, null, null, 2, 'Consumable', 47),
    ('A', 'RA-A-045', 'Spidol papan tulis hitam', 'consumable', 2, null, null, 2, 'Consumable', 48),
    ('A', 'RA-A-046', 'Spidol papan tulis hijau', 'consumable', 1, null, null, 1, 'Consumable', 49),
    ('A', 'RA-A-047', 'gembok', 'consumable', 4, null, null, 4, 'Consumable', 50),
    ('A', 'RA-A-048', 'baterai A3 1.5V', 'consumable', 6, null, null, 6, 'Consumable', 51),
    ('A', 'RA-A-049', 'Spidol papan tulis biru', 'consumable', 2, null, 1, 3, 'Consumable', 52),
    ('A', 'RA-A-050', 'DVD-R', 'consumable', 1, null, null, 1, 'Consumable', 53),
    ('A', 'RA-A-051', 'wrping', 'unclassified', 4, null, null, null, null, 54),
    ('B', 'RA-B-001', 'Power Suplay Output 24VDC 6.5A', 'consumable', 1, null, null, 1, 'Consumable', 58),
    ('B', 'RA-B-002', 'Limit Switch D4V', 'consumable', 9, null, null, 9, 'Consumable', 59),
    ('B', 'RA-B-003', 'Thermal Overload Mitsubishi', 'consumable', null, null, null, null, 'Consumable', 60),
    ('B', 'RA-B-004', 'Kabel Tie', 'consumable', null, null, null, null, 'Consumable', 61),
    ('B', 'RA-B-005', 'Fan Cooler Socket', 'consumable', 1, null, null, 1, 'Consumable', 62),
    ('B', 'RA-B-006', 'MCB Auto Breaker', 'consumable', 1, null, null, 1, 'Consumable', 63),
    ('B', 'RA-B-007', 'Magnetic Contractor', 'consumable', 3, null, null, 3, 'Consumable', 64),
    ('B', 'RA-B-008', 'Schneider Circuit Breaker', 'consumable', null, null, null, null, 'Consumable', 65),
    ('B', 'RA-B-009', 'MCB 1 Channel', 'consumable', 7, null, null, 7, 'Consumable', 66),
    ('B', 'RA-B-010', 'MCB 2 Channel', 'consumable', 1, null, null, 1, 'Consumable', 67),
    ('B', 'RA-B-011', 'Selenoid Valve', 'consumable', 2, null, null, 2, 'Consumable', 68),
    ('B', 'RA-B-012', 'Trafo Lampu 40Watt', 'consumable', 1, null, null, 1, 'Consumable', 69),
    ('B', 'RA-B-013', 'Cirkuit Breaker Siemens', 'consumable', 1, null, null, 1, 'Consumable', 70),
    ('B', 'RA-B-014', 'OMRON H3CR (Timer)', 'consumable', 1, null, null, 1, 'Consumable', 71),
    ('B', 'RA-B-015', 'Mouse', 'inventory', null, null, null, null, 'Inventory', 72),
    ('B', 'RA-B-016', 'Fan 10Watt', 'consumable', null, null, null, null, 'Consumable', 73),
    ('B', 'RA-B-017', 'Senter', 'inventory', 1, null, null, 1, 'Inventory', 74),
    ('B', 'RA-B-018', 'Current Transformer', 'consumable', 2, null, null, 2, 'Consumable', 75),
    ('B', 'RA-B-019', 'Relay Kodok 12V 30A', 'consumable', null, null, null, null, 'Consumable', 76),
    ('B', 'RA-B-020', 'No-Fuse Breaker Mitsubishi', 'consumable', 1, null, null, 1, 'Consumable', 77),
    ('B', 'RA-B-021', 'Eaton Moeller', 'consumable', 1, null, null, 1, 'Consumable', 78),
    ('B', 'RA-B-022', 'Photoelectric Switch Omron', 'consumable', 2, null, null, 2, 'Consumable', 79),
    ('B', 'RA-B-023', 'Stop Kontak', 'consumable', null, null, null, null, 'Consumable', 80),
    ('B', 'RA-B-024', 'Socket Fluks 16A', 'consumable', 1, null, null, 1, 'Consumable', 81),
    ('B', 'RA-B-025', 'Nozzle Jet Cleaner', 'consumable', 3, null, null, 3, 'Consumable', 82),
    ('B', 'RA-B-026', 'Tutup Fan', 'consumable', 4, null, null, 4, 'Consumable', 83),
    ('B', 'RA-B-027', 'Heater Mitsubishi 11A', 'consumable', 1, null, null, 1, 'Consumable', 84),
    ('B', 'RA-B-028', 'Kontraktor Fuji', 'consumable', 9, null, null, 9, 'Consumable', 85),
    ('B', 'RA-B-029', 'Kontraktor Mitsubishi', 'consumable', 1, null, null, 1, 'Consumable', 86),
    ('B', 'RA-B-030', 'Cirkuit Breaker Mitsubishi', 'consumable', 1, null, null, 1, 'Consumable', 87),
    ('B', 'RA-B-031', 'Blok Terminal', 'consumable', 1, null, null, 1, 'Consumable', 88),
    ('B', 'RA-B-032', 'Kontraktor LC1D 3 Pole', 'consumable', 2, null, null, 2, 'Consumable', 89),
    ('B', 'RA-B-034', 'Magnet', 'consumable', 1, null, null, 1, 'Consumable', 90),
    ('B', 'RA-B-035', 'Casing Lampu LED', 'consumable', 4, null, null, 4, 'Consumable', 91),
    ('B', 'RA-B-036', 'Push Button', 'consumable', 5, null, null, 5, 'Consumable', 92),
    ('B', 'RA-B-037', 'Thermal Overload Relay', 'consumable', 14, null, null, 14, 'Consumable', 93),
    ('B', 'RA-B-038', 'Rotary Encoder Omron', 'consumable', 1, null, null, 1, 'Consumable', 94),
    ('B', 'RA-B-039', 'Solid State Relay Omron', 'consumable', 2, null, null, 2, 'Consumable', 95),
    ('B', 'RA-B-040', 'MCCB BW50EAG 3P 40A', 'consumable', 1, null, null, 1, 'Consumable', 96),
    ('B', 'RA-B-041', 'Push Button Harmony', 'consumable', 1, null, null, 1, 'Consumable', 97),
    ('B', 'RA-B-042', 'Control Box 3 Hole Schneider', 'consumable', 5, null, null, 5, 'Consumable', 98),
    ('B', 'RA-B-043', 'Relay RMI', 'consumable', 16, null, null, 16, 'Consumable', 99),
    ('B', 'RA-B-044', 'Mata Gerinda', 'consumable', null, null, 4, 4, 'Consumable', 100),
    ('B', 'RA-B-045', 'Stepper Motor', 'consumable', null, null, null, null, 'Consumable', 101),
    ('B', 'RA-B-046', 'Step Driver', 'consumable', null, null, null, null, 'Consumable', 102),
    ('B', 'RA-B-047', 'Project Board', 'consumable', 1, null, null, 1, 'Consumable', 103),
    ('B', 'RA-B-048', 'Option Board Card', 'consumable', 1, null, null, 1, 'Consumable', 104),
    ('B', 'RA-B-049', 'Amplas', 'consumable', 1, null, null, 1, 'Consumable', 105),
    ('B', 'RA-B-050', 'Busa Poles Gerinda Merah', 'consumable', 2, null, null, 2, 'Consumable', 106),
    ('B', 'RA-B-051', 'Busa Poles Gerinda Hitam', 'unclassified', 1, null, null, null, null, 107),
    ('C', 'RA-C-057', 'Box Control Start Stop keset', 'consumable', 1, null, null, null, 'Consumable', 111),
    ('C', 'RA-C-001', 'JBX 2.5N', 'consumable', 1, null, null, 1, 'Consumable', 112),
    ('C', 'RA-C-002', 'Terminal Blok Model Ten', 'consumable', 1, null, null, 1, 'Consumable', 113),
    ('C', 'RA-C-003', 'Fort TBR-30', 'consumable', 1, null, null, 1, 'Consumable', 114),
    ('C', 'RA-C-004', 'Hanyong HYTM-15', 'consumable', 1, null, null, 1, 'Consumable', 115),
    ('C', 'RA-C-005', 'Sakdu 6', 'consumable', 1, null, null, 1, 'Consumable', 116),
    ('C', 'RA-C-006', 'Pengikat Kabel', 'consumable', null, null, null, null, 'Consumable', 117),
    ('C', 'RA-C-007', 'Phoenix Contact', 'consumable', 1, null, null, 1, 'Consumable', 118),
    ('C', 'RA-C-008', 'Phoenix Contact Schneider', 'consumable', 1, null, null, 1, 'Consumable', 119),
    ('C', 'RA-C-009', 'Stopper Terminal Blok', 'consumable', 2, null, null, 2, 'Consumable', 120),
    ('C', 'RA-C-010', 'Terminal Blok Wielen', 'consumable', 1, null, null, 1, 'Consumable', 121),
    ('C', 'RA-C-011', 'Terminal Push Button Schneider', 'consumable', 1, null, null, 1, 'Consumable', 122),
    ('C', 'RA-C-012', 'Spuindo Terminal', 'consumable', 3, null, null, 3, 'Consumable', 123),
    ('C', 'RA-C-013', 'Phoenix Contact D', 'consumable', 1, null, null, 1, 'Consumable', 124),
    ('C', 'RA-C-014', 'Terminal Viking', 'consumable', 1, null, null, 1, 'Consumable', 125),
    ('C', 'RA-C-015', 'Cover MCB', 'consumable', 14, null, null, 14, 'Consumable', 126),
    ('C', 'RA-C-016', 'Rumah Sekring', 'consumable', 6, null, null, 6, 'Consumable', 127),
    ('C', 'RA-C-017', 'Terminal Blok 6N', 'consumable', 6, null, null, 6, 'Consumable', 128),
    ('C', 'RA-C-018', 'ES4', 'consumable', 1, null, null, 1, 'Consumable', 129),
    ('C', 'RA-C-019', 'TBR 30', 'consumable', 1, null, null, 1, 'Consumable', 130),
    ('C', 'RA-C-020', 'KTP Diplir', 'consumable', 1, null, null, 1, 'Consumable', 131),
    ('C', 'RA-C-021', 'SUK-E', 'consumable', 1, null, null, 1, 'Consumable', 132),
    ('C', 'RA-C-022', 'Stopper Din Rail', 'consumable', 1, null, null, 1, 'Consumable', 133),
    ('C', 'RA-C-023', 'Strip Block Terminal', 'consumable', 1, null, null, 1, 'Consumable', 134),
    ('C', 'RA-C-024', 'Netviel Fiber Optik', 'consumable', 2, null, null, 2, 'Consumable', 135),
    ('C', 'RA-C-025', 'Fort LA115-A', 'consumable', 2, null, null, 2, 'Consumable', 136),
    ('C', 'RA-C-026', 'Shutter Button', 'consumable', 1, null, null, 1, 'Consumable', 137),
    ('C', 'RA-C-027', 'Nuzzle Jet', 'consumable', 1, null, null, 1, 'Consumable', 138),
    ('C', 'RA-C-028', 'Cable Gland', 'consumable', 1, null, null, 1, 'Consumable', 139),
    ('C', 'RA-C-029', 'Thermal Overload Relay Mitsubishi', 'consumable', 1, null, null, 1, 'Consumable', 140),
    ('C', 'RA-C-030', 'Tempat Relay (housing) 6 Kaki', 'consumable', 5, null, null, 5, 'Consumable', 141),
    ('C', 'RA-C-031', 'Tempat Relay (housing) 6 Kaki Omron', 'consumable', 2, null, null, 2, 'Consumable', 142),
    ('C', 'RA-C-032', 'Tempat Relay (housing) 6 Kaki Omron', 'consumable', 3, null, null, 3, 'Consumable', 143),
    ('C', 'RA-C-033', 'Tempat Relay (housing) MT740', 'consumable', 2, null, null, 2, 'Consumable', 144),
    ('C', 'RA-C-034', 'Tempat Relay (housing) 12 Kaki', 'consumable', 2, null, null, 2, 'Consumable', 145),
    ('C', 'RA-C-035', 'Push Button Red', 'consumable', 13, null, null, 13, 'Consumable', 146),
    ('C', 'RA-C-036', 'Push Button Green', 'consumable', 26, 3, null, 23, 'Consumable', 147),
    ('C', 'RA-C-037', 'Terminal Blok', 'consumable', 2, null, null, 2, 'Consumable', 148),
    ('C', 'RA-C-038', 'SACB-', 'consumable', 7, null, null, 7, 'Consumable', 149),
    ('C', 'RA-C-039', 'SA-CA', 'consumable', 5, null, null, 5, 'Consumable', 150),
    ('C', 'RA-C-040', 'Terminal AWG24-12', 'consumable', 4, null, null, 4, 'Consumable', 151),
    ('C', 'RA-C-041', 'Stopper Silikon', 'consumable', 1, null, null, 1, 'Consumable', 152),
    ('C', 'RA-C-042', 'Push Button Red Box Harmony', 'consumable', 22, null, null, 22, 'Consumable', 153),
    ('C', 'RA-C-043', 'Push Button Red Box Tent', 'consumable', 42, 2, null, 40, 'Consumable', 154),
    ('C', 'RA-C-044', 'Terminal Blok Fort One', 'consumable', 2, null, null, 2, 'Consumable', 155),
    ('C', 'RA-C-045', 'Push Button Green Box Harmony', 'consumable', 22, 4, null, 18, 'Consumable', 156),
    ('C', 'RA-C-046', 'Push Button Green Box IDEC', 'consumable', 40, 3, null, 37, 'Consumable', 157),
    ('C', 'RA-C-008-2', 'engie treper (Perlu verifikasi)', 'consumable', 1, null, null, 2, 'Consumable', 158),
    ('C', 'RA-C-047', 'Push Button Green Box IDEC', 'consumable', 36, null, null, 36, 'Consumable', 159),
    ('C', 'RA-C-048', 'Push Button Black Box Schneider', 'consumable', 35, null, null, 35, 'Consumable', 160),
    ('C', 'RA-C-049', 'Push Button Red Box IDEC', 'consumable', 21, null, null, 21, 'Consumable', 161),
    ('C', 'RA-C-050', 'Pilot Lamp Red Box Tent', 'consumable', 60, null, null, 60, 'Consumable', 162),
    ('C', 'RA-C-051', 'Pilot Lamp Orange Box Harmony', 'consumable', 19, null, null, 19, 'Consumable', 163),
    ('C', 'RA-C-052', 'Filter Fan', 'consumable', 1, null, null, 1, 'Consumable', 164),
    ('C', 'RA-C-053', 'MCB', 'consumable', 17, null, null, 17, 'Consumable', 165),
    ('C', 'RA-C-054', 'Push Button Green Box Tent', 'consumable', 26, null, null, 26, 'Consumable', 166),
    ('C', 'RA-C-055', 'Relay MY2N-65', 'consumable', 2, null, null, 2, 'Consumable', 167),
    ('C', 'RA-C-056', 'Relay MY4N-65', 'consumable', 5, null, null, 5, 'Consumable', 168),
    ('C', 'RA-C-057-2', 'Relay VDC', 'consumable', 56, null, null, 56, 'Consumable', 169),
    ('C', 'RA-C-058', 'Relay VAC', 'consumable', 17, null, null, 17, 'Consumable', 170),
    ('C', 'RA-C-001-2', 'Tapping Oil', 'inventory', 1, null, null, 1, 'Inventory', 171),
    ('C', 'RA-C-002-2', 'Gerinda Tangan', 'inventory', 1, null, null, 1, 'Inventory', 172),
    ('C', 'RA-C-003-2', 'Tracker Kaki 3', 'consumable', 1, null, null, 1, 'Consumable', 173),
    ('C', 'RA-C-004-2', 'TBR-10', 'consumable', null, null, null, 1, 'Consumable', 174),
    ('C', 'RA-C-005-2', 'Paralon', 'consumable', 1, null, null, 1, 'Consumable', 175),
    ('C', 'RA-C-006-2', 'Juction box', 'consumable', 8, null, null, 8, 'Consumable', 176),
    ('C', 'RA-C-007-2', 'mata pipa', 'unclassified', 2, null, null, null, null, 177),
    ('D', 'RA-D-001', 'Klip Kabel', 'consumable', 2, null, null, 2, 'Consumable', 181),
    ('D', 'RA-D-002', 'Mata solder', 'consumable', 5, null, null, 5, 'Consumable', 182),
    ('D', 'RA-D-003', 'Penyedot timah', 'inventory', 3, null, null, 3, 'Inventory', 183),
    ('D', 'RA-D-004', 'Casing DB25', 'consumable', 4, null, null, 4, 'Consumable', 184),
    ('D', 'RA-D-005', 'skun kabel gepeng 2,8mm', 'consumable', 1, null, null, 1, 'Consumable', 185),
    ('D', 'RA-D-006', 'Jack Soket DC MALE DIN', 'consumable', 2, null, null, 2, 'Consumable', 186),
    ('D', 'RA-D-007', 'Kopling N-COLOR', 'consumable', 1, 1, null, null, 'Consumable', 187),
    ('D', 'RA-D-008', 'Konektor kabel listrik', 'consumable', 1, null, null, 1, 'Consumable', 188),
    ('D', 'RA-D-009', 'Konektor PCB DB9 F Websong', 'consumable', 1, null, null, 1, 'Consumable', 189),
    ('D', 'RA-D-010', 'Sekrup Pengencang', 'consumable', 1, null, null, 1, 'Consumable', 190),
    ('D', 'RA-D-011', 'Skun Kabel FERRULE', 'consumable', 1, null, null, 1, 'Consumable', 191),
    ('D', 'RA-D-012', 'Terminal Blok Konektor', 'consumable', 1, 1, null, null, 'Consumable', 192),
    ('D', 'RA-D-013', 'vinil kabel V8', 'consumable', 3, null, null, 3, 'Consumable', 193),
    ('D', 'RA-D-014', 'FORT END PLATE TBR-10A', 'consumable', 1, null, null, 1, 'Consumable', 194),
    ('D', 'RA-D-015', 'Sarung Pelindung Konektor Kabel', 'consumable', 2, null, null, 2, 'Consumable', 195),
    ('D', 'RA-D-016', 'Konektor RJ45', 'consumable', 2, null, null, 2, 'Consumable', 196),
    ('D', 'RA-D-017', 'Konektor UTP RJ45 SHIELDED', 'consumable', 2, null, null, 2, 'Consumable', 197),
    ('D', 'RA-D-018', 'Konektor RJ45 CRYSTAL', 'consumable', 2, null, null, 2, 'Consumable', 198),
    ('D', 'RA-D-019', 'vinil kabel V14', 'consumable', 3, null, null, 3, 'Consumable', 199),
    ('D', 'RA-D-020', 'vinil kabel V2', 'consumable', 4, null, null, 4, 'Consumable', 200),
    ('D', 'RA-D-021', 'KABEL TIS 2,5x100 MM', 'consumable', 3, null, null, 3, 'Consumable', 201),
    ('D', 'RA-D-022', 'KABEL TIS 2,5x200 MM', 'consumable', 6, null, null, 6, 'Consumable', 202),
    ('D', 'RA-D-023', 'CABLE TIES LABEL', 'consumable', 4, null, null, 4, 'Consumable', 203),
    ('D', 'RA-D-024', 'IGLIDUR J SLEEVE BEARING', 'consumable', 1, null, null, 1, 'Consumable', 204),
    ('D', 'RA-D-025', 'Paku rivet', 'consumable', 1, null, null, 1, 'Consumable', 205),
    ('D', 'RA-D-026', 'Paku Baja', 'consumable', 1, null, null, 1, 'Consumable', 206),
    ('D', 'RA-D-027', 'vinil kabel V125', 'consumable', 7, null, null, 7, 'Consumable', 207),
    ('D', 'RA-D-028', 'STIKER BAHAYA LISTRIK', 'consumable', 1, null, null, 1, 'Consumable', 208),
    ('D', 'RA-D-029', 'VINIL KABEL V 200', 'consumable', 5, null, null, 5, 'Consumable', 209),
    ('D', 'RA-D-030', 'BAUT KNOP PLASTIC', 'consumable', 1, null, null, 1, 'Consumable', 210),
    ('D', 'RA-D-031', 'SAKLAR KUNCI ELECTRIC', 'consumable', 1, null, null, 1, 'Consumable', 211),
    ('D', 'RA-D-031-2', 'SKUN VINIL', 'consumable', 1, null, null, 1, 'Consumable', 212),
    ('D', 'RA-D-032', 'LAMP PILOT', 'consumable', 1, null, null, 1, 'Consumable', 213),
    ('D', 'RA-D-033', 'BRACET BESI', 'consumable', 1, null, null, 1, 'Consumable', 214),
    ('D', 'RA-D-034', 'COVER VGA DB9', 'consumable', 3, null, null, 3, 'Consumable', 215),
    ('D', 'RA-D-035', 'peluru stain less teel', 'consumable', 1, null, null, 1, 'Consumable', 216),
    ('D', 'RA-D-036', 'SEKRING TABUNG KACA', 'consumable', 1, null, null, 1, 'Consumable', 217),
    ('D', 'RA-D-037', 'BAUT L TANAM', 'consumable', 1, null, null, 1, 'Consumable', 218),
    ('D', 'RA-D-038', 'SET BAUT DAN MUR', 'consumable', 1, null, null, 1, 'Consumable', 219),
    ('D', 'RA-D-039', 'NUT M5', 'consumable', 1, null, null, 1, 'Consumable', 220),
    ('D', 'RA-D-040', '5CM SPACER', 'consumable', 1, null, null, 1, 'Consumable', 221),
    ('D', 'RA-D-041', 'CONECTOR BNC - KWE', 'consumable', 1, null, null, 1, 'Consumable', 222),
    ('D', 'RA-D-042', 'FITTING SHOK 10X12 MM', 'consumable', 1, null, null, 1, 'Consumable', 223),
    ('D', 'RA-D-043', 'SPEED CONTROL 8X8', 'consumable', 1, null, null, 1, 'Consumable', 224),
    ('D', 'RA-D-044', 'BAUT U, BAUT 4MM', 'consumable', 1, null, null, 1, 'Consumable', 225),
    ('D', 'RA-D-045', 'FITTING 1/2X12', 'consumable', 1, null, null, 1, 'Consumable', 226),
    ('D', 'RA-D-046', 'FITTING 1/8X10MM', 'consumable', 2, null, null, 1, 'Consumable', 227),
    ('D', 'RA-D-047', 'T 10X10MM', 'consumable', 1, 1, null, null, 'Consumable', 228),
    ('D', 'RA-D-048', 'SHOK REDUCE 4X6MM', 'consumable', 1, 1, null, null, 'Consumable', 229),
    ('D', 'RA-D-049', 'FITTING 6X8MM', 'consumable', 1, null, null, 1, 'Consumable', 230),
    ('D', 'RA-D-050', 'Y 6X6MM', 'consumable', 1, null, null, 1, 'Consumable', 231),
    ('D', 'RA-D-051', 'FITTING 1/4X8MM', 'consumable', 1, null, null, 1, 'Consumable', 232),
    ('D', 'RA-D-052', 'T 8X8MM', 'consumable', 1, null, null, 1, 'Consumable', 233),
    ('D', 'RA-D-053', 'Y 8X8MM', 'consumable', 1, null, null, 1, 'Consumable', 234),
    ('D', 'RA-D-054', 'T 6X6MM', 'consumable', 1, null, null, 1, 'Consumable', 235),
    ('D', 'RA-D-055', 'FITTING Y 10X10MM', 'consumable', 1, null, null, 1, 'Consumable', 236),
    ('D', 'RA-D-056', 'FITTING T 12X12MM', 'consumable', 1, null, null, 1, 'Consumable', 237),
    ('D', 'RA-D-057', 'SPEED CONTROL', 'consumable', 1, null, null, 1, 'Consumable', 238),
    ('D', 'RA-D-058', 'FILTER', 'consumable', 1, null, null, 1, 'Consumable', 239),
    ('D', 'RA-D-059', 'FITTING 1/8X12MM', 'consumable', 1, null, null, 1, 'Consumable', 240),
    ('D', 'RA-D-060', 'ACC FITTING', 'consumable', 1, null, null, 1, 'Consumable', 241),
    ('D', 'RA-D-061', 'FITTING 1/4X10MM', 'consumable', 1, null, null, 1, 'Consumable', 242),
    ('D', 'RA-D-062', 'DRAT NAPPLE', 'consumable', 1, null, null, 1, 'Consumable', 243),
    ('D', 'RA-D-063', 'ELBOW M5X6', 'consumable', 1, null, null, 1, 'Consumable', 244),
    ('D', 'RA-D-064', 'FITTING 1/8X8MM', 'consumable', 1, null, null, 1, 'Consumable', 245),
    ('D', 'RA-D-065', 'ELBOW DRAT 10/12', 'consumable', 1, null, null, 1, 'Consumable', 246),
    ('D', 'RA-D-066', 'KEPALA GAS PORTABLE', 'inventory', 1, null, null, 1, 'Inventory', 247),
    ('D', 'RA-D-067', 'KABEL RS/232', 'consumable', 1, null, null, 1, 'Consumable', 248),
    ('D', 'RA-D-068', 'KARET', 'consumable', 1, null, null, 1, 'Consumable', 249),
    ('D', 'RA-D-069', 'KABEL PRINTER', 'inventory', 2, null, null, 2, 'Inventory', 250),
    ('D', 'RA-D-070', 'KABEL VGA SPLITTER', 'inventory', 1, null, null, 1, 'Inventory', 251),
    ('D', 'RA-D-071', 'KLIP KABEL', 'consumable', 1, null, null, 1, 'Consumable', 252),
    ('D', 'RA-D-072', 'KLIP KABEL PAKU BETON', 'consumable', 1, null, null, 1, 'Consumable', 253),
    ('D', 'RA-D-073', 'GAGANG TARIKAN D', 'inventory', 1, null, null, 1, 'Inventory', 254),
    ('D', 'RA-D-074', 'KLEM KABEL', 'inventory', 1, null, null, 1, 'Inventory', 255),
    ('D', 'RA-D-075', 'ACC MESIN LAS', 'inventory', 1, null, null, 1, 'Inventory', 256),
    ('D', 'RA-D-076', 'KABEL HDMI AACBJ', 'inventory', 1, null, null, 1, 'Inventory', 257),
    ('D', 'RA-D-077', 'SKUN FERULESS E7508', 'consumable', 2, null, null, 2, 'Consumable', 258),
    ('D', 'RA-D-078', 'SKUN KABEL TUSUK', 'consumable', 4, null, null, 4, 'Consumable', 259),
    ('D', 'RA-D-079', 'SKUN KABEL', 'consumable', 1, null, null, 1, 'Consumable', 260),
    ('D', 'RA-D-080', 'mata geraji', 'consumable', 1, null, null, 1, 'Consumable', 261),
    ('D', 'RA-D-081', 'premium tct multocutter', 'inventory', 1, null, null, 1, 'Inventory', 262),
    ('D', 'RA-D-082', 'skun y', 'consumable', 11, null, null, 11, 'Consumable', 263),
    ('D', 'RA-D-083', 'skun ring', 'consumable', 1, null, null, 1, 'Consumable', 264),
    ('D', 'RA-D-084', 'satu set bracet', 'consumable', 1, null, null, 1, 'Consumable', 265),
    ('D', 'RA-D-085', 'conektor hdmi', 'inventory', 1, null, null, 1, 'Inventory', 266),
    ('D', 'RA-D-086', 'sekring tipe tancap', 'consumable', 1, null, null, 1, 'Consumable', 267),
    ('D', 'RA-D-087', 'gender cheger', 'consumable', 1, null, null, 1, 'Consumable', 268),
    ('D', 'RA-D-088', 'spidol penanda ujung panjang', 'inventory', 1, null, null, 1, 'Inventory', 269),
    ('D', 'RA-D-089', 'kabel fiber optik', 'consumable', 1, null, null, 1, 'Consumable', 270),
    ('D', 'RA-D-090', 'tang skun', 'consumable', 1, null, null, 1, 'Consumable', 271),
    ('D', 'RA-D-091', 'PROXIMITY SENSOR', 'consumable', 2, 1, null, 1, 'Consumable', 272),
    ('D', 'RA-D-092', 'PHOTO SENSOR', 'consumable', 1, null, null, 1, 'Consumable', 273),
    ('D', 'RA-D-093', 'KABEL DAYA MONITOR', 'consumable', 1, null, null, 1, 'Consumable', 274),
    ('D', 'RA-D-094', 'TERMINAL BLOK UK 3N', 'consumable', 1, null, null, 1, 'Consumable', 275),
    ('D', 'RA-D-095', 'KABEL USB', 'consumable', 1, null, null, 1, 'Consumable', 276),
    ('D', 'RA-D-096', 'PUSH BUTTON', 'consumable', 1, null, null, 1, 'Consumable', 277),
    ('D', 'RA-D-097', 'KABEL AUDIO', 'consumable', 1, null, null, 1, 'Consumable', 278),
    ('D', 'RA-D-098', 'KABEL DATA', 'consumable', 1, null, null, 1, 'Consumable', 279),
    ('D', 'RA-D-099', 'PEMOTONG FIBER OPTIK', 'consumable', 2, null, null, 2, 'Consumable', 280),
    ('D', 'RA-D-100', 'KNOP CONTROL EX5MK2', 'consumable', 1, null, null, 1, 'Consumable', 281),
    ('D', 'RA-D-101', 'AUTONICS CR18-8DP', 'consumable', 5, null, null, 5, 'Consumable', 282),
    ('D', 'RA-D-102', 'SAFETY EMERGENCY SWITCH', 'consumable', 4, null, null, 4, 'Consumable', 283),
    ('D', 'RA-D-103', 'KABEL DAYA AC', 'consumable', 1, null, null, 1, 'Consumable', 284),
    ('D', 'RA-D-104', 'KABEL LAN', 'consumable', 4, null, null, 4, 'Consumable', 285),
    ('D', 'RA-D-105', 'AC SERVO MOTOR HC-8H023-512', 'consumable', 1, null, null, 1, 'Consumable', 286),
    ('D', 'RA-D-106', 'KTR-50MM', 'unclassified', 1, null, null, null, null, 287),
    ('E', 'RA-E-019', 'digital input modul QX40', 'consumable', 3, null, null, 3, 'Consumable', 291),
    ('E', 'RA-E-001', 'Power Supply 24V', 'consumable', 4, null, null, 4, 'Consumable', 292),
    ('E', 'RA-E-002', 'Rak Ekspansi PLC Mitsubishi MDL Q312B', 'consumable', 1, null, null, 1, 'Consumable', 293),
    ('E', 'RA-E-003', 'PLC Omron Seri CQM1H', 'consumable', 1, null, null, 1, 'Consumable', 294),
    ('E', 'RA-E-004', 'WLAN TP-LINK + Adaptor', 'consumable', 1, null, null, 1, 'Consumable', 295),
    ('E', 'RA-E-005', 'CPU Unit Mitsubishi A1SJH', 'consumable', 1, null, null, 1, 'Consumable', 296),
    ('E', 'RA-E-006', 'Water Level Control Omron', 'consumable', null, null, null, null, 'Consumable', 297),
    ('E', 'RA-E-007', 'WLAN TP-LINK ACER AX10', 'consumable', 1, null, null, 1, 'Consumable', 298),
    ('E', 'RA-E-008', 'WLAN TP-LINK TL-WR941HP', 'consumable', null, null, null, null, 'Consumable', 299),
    ('E', 'RA-E-009', 'Vacuum Pump/Generator VMECA', 'consumable', null, null, null, null, 'Consumable', 300),
    ('E', 'RA-E-010', 'Controller SG8030J Oriental Motor', 'consumable', 1, null, null, 1, 'Consumable', 301),
    ('E', 'RA-E-011', 'Tower Lamp Hijau', 'consumable', 1, null, null, 1, 'Consumable', 302),
    ('E', 'RA-E-012', 'Limit Switch Omron', 'consumable', 1, null, null, 1, 'Consumable', 303),
    ('E', 'RA-E-013', 'Altivar Sheider', 'consumable', 1, null, null, 1, 'Consumable', 304),
    ('E', 'RA-E-014', 'Pic mitsubhisi', 'consumable', null, null, null, null, 'Consumable', 305),
    ('E', 'RA-E-015', 'Lane tester', 'inventory', 2, null, null, 2, 'Inventory', 306),
    ('E', 'RA-E-016', 'mitsubishi QJ61BT11N', 'consumable', 4, null, null, 4, 'Consumable', 307),
    ('E', 'RA-E-017', 'mitsubishi servo amplifier', 'consumable', 1, null, null, 1, 'Consumable', 308),
    ('E', 'RA-E-018', 'mitsubishi intelligent unit', 'consumable', 1, null, null, 1, 'Consumable', 309),
    ('E', 'RA-E-020', 'mitsubishi electric QJ71C24J', 'consumable', 1, null, null, 1, 'Consumable', 310),
    ('E', 'RA-E-021', 'mitsubishi MR-TB20', 'consumable', 1, null, null, 1, 'Consumable', 311),
    ('E', 'RA-E-022', 'mitsubishi electric QJ61BP11M', 'consumable', 1, null, null, 1, 'Consumable', 312),
    ('E', 'RA-E-023', 'Pengontrol Suhu ascon tecnology', 'consumable', 1, null, null, 1, 'Consumable', 313),
    ('E', 'RA-E-024', 'Volt meter digital model HZ-AK1', 'consumable', 1, null, null, 1, 'Consumable', 314),
    ('E', 'RA-E-025', 'Mitsubishi Electric ethernet I/F QJ71E71', 'consumable', 1, null, null, 1, 'Consumable', 315),
    ('E', 'RA-E-026', 'Pisco tube UB-0640-B', 'consumable', 1, null, null, 1, 'Consumable', 316),
    ('E', 'RA-E-027', 'KSS MARKER TUBE OMT 2,5', 'consumable', 1, null, null, 1, 'Consumable', 317),
    ('E', 'RA-E-028', 'KSS MARKER TUBE OMT 5,0', 'consumable', 1, null, null, 1, 'Consumable', 318),
    ('E', 'RA-E-029', 'KSS MARKER TUBE OMT 4,0', 'consumable', 1, null, null, 1, 'Consumable', 319),
    ('E', 'RA-E-030', 'KSS MARKER TUBE OMT 6,0', 'consumable', 1, null, null, 1, 'Consumable', 320),
    ('E', 'RA-E-031', 'KSS MARKER TUBE OMT 3,4', 'consumable', 1, null, null, 1, 'Consumable', 321),
    ('E', 'RA-E-032', 'KSS MARKER TUBE OMT 3,0', 'consumable', 1, null, null, 1, 'Consumable', 322),
    ('F', 'RA-F-001', 'Bracet Torqiu 0,54 Nm', 'consumable', 1, null, null, 1, 'Consumable', 323),
    ('F', 'RA-F-002', 'KAWAT LAS 2.0 X 300 MM', 'consumable', 1, null, null, 1, 'Consumable', 324),
    ('F', 'RA-F-003', 'KAWAT LAS 3.2 MM', 'consumable', 1, null, null, 1, 'Consumable', 325),
    ('F', 'RA-F-004', 'MATA GRINDA BENZ 100X12X16MM', 'consumable', 1, null, null, 1, 'Consumable', 326),
    ('F', 'RA-F-005', 'WOOL FLET 100MM', 'consumable', 1, null, null, 1, 'Consumable', 327),
    ('F', 'RA-F-006', 'AMPLAS GRINDA CAB FLAP DISC SIZE 4', 'consumable', 3, null, null, 3, 'Consumable', 328),
    ('F', 'RA-F-007', 'MATA POTONG GRINDA', 'consumable', 5, null, null, 5, 'Consumable', 329),
    ('F', 'RA-F-008', 'FORT PANEL METER', 'consumable', null, null, null, null, 'Consumable', 330),
    ('F', 'RA-F-009', 'BAUT DRILLING', 'consumable', 1, null, null, 1, 'Consumable', 331),
    ('F', 'RA-F-010', 'KAWAT LAS 1.6X250MM', 'consumable', 1, null, null, 1, 'Consumable', 332),
    ('F', 'RA-F-011', 'WD-40', 'consumable', 1, null, null, 1, 'Consumable', 333),
    ('F', 'RA-F-012', 'BH M8X70', 'consumable', 1, null, null, 1, 'Consumable', 334),
    ('F', 'RA-F-013', 'BH M6X50', 'consumable', 1, null, null, 1, 'Consumable', 335),
    ('F', 'RA-F-014', 'BH M6X70', 'consumable', 1, null, null, 1, 'Consumable', 336),
    ('F', 'RA-F-015', 'BH M6X15', 'consumable', 1, null, null, 1, 'Consumable', 337),
    ('F', 'RA-F-016', 'BH UNS 4.6', 'consumable', 1, null, null, 1, 'Consumable', 338),
    ('F', 'RA-F-017', 'SET BAUT MUR DAN RING', 'consumable', 1, null, null, 1, 'Consumable', 339),
    ('F', 'RA-F-018', 'BH M8', 'consumable', 1, null, null, 1, 'Consumable', 340),
    ('F', 'RA-F-019', 'BAUT MUR', 'consumable', 2, null, null, 2, 'Consumable', 341),
    ('F', 'RA-F-020', 'BH M10X25', 'consumable', 1, null, null, 1, 'Consumable', 342),
    ('F', 'RA-F-021', 'RIVET 435', 'consumable', 1, null, null, 1, 'Consumable', 343),
    ('F', 'RA-F-022', 'BAUT ANGKUR', 'consumable', 1, null, null, 1, 'Consumable', 344),
    ('F', 'RA-F-023', 'BAUT TANAM', 'consumable', 1, null, null, 1, 'Consumable', 345),
    ('F', 'RA-F-024', 'SKUN FERULLES KUNING E0508', 'consumable', 1, null, null, 1, 'Consumable', 346),
    ('F', 'RA-F-025', 'BH M5X50', 'consumable', 1, null, null, 1, 'Consumable', 347),
    ('F', 'RA-F-026', 'BL M10X35', 'consumable', 1, null, null, 1, 'Consumable', 348),
    ('F', 'RA-F-027', 'BL M5X40', 'consumable', 1, null, null, 1, 'Consumable', 349),
    ('F', 'RA-F-028', 'JS.SS 10X25', 'consumable', 1, null, null, 1, 'Consumable', 350),
    ('F', 'RA-F-029', 'SKUN FERULLES MERAH E0508', 'consumable', 1, null, null, 1, 'Consumable', 351),
    ('F', 'RA-F-030', 'SKUN FERULLES PUTIH TE0508', 'consumable', 1, null, null, 1, 'Consumable', 352),
    ('F', 'RA-F-031', 'NUT M19', 'consumable', 1, null, null, 1, 'Consumable', 353),
    ('F', 'RA-F-032', 'NUT M8', 'consumable', 3, null, null, 3, 'Consumable', 354),
    ('F', 'RA-F-033', 'NUT', 'consumable', 1, null, null, 1, 'Consumable', 355),
    ('F', 'RA-F-034', 'NUT M10', 'consumable', 1, null, null, 1, 'Consumable', 356),
    ('F', 'RA-F-035', 'NUT M6', 'consumable', 1, null, null, 1, 'Consumable', 357),
    ('F', 'RA-F-036', 'NUT M15', 'consumable', 1, null, null, 1, 'Consumable', 358),
    ('F', 'RA-F-037', 'RING 6MM', 'consumable', 1, null, null, 1, 'Consumable', 359),
    ('F', 'RA-F-038', 'BAUT MESIN', 'consumable', 1, null, null, 1, 'Consumable', 360),
    ('F', 'RA-F-039', 'BAUT KECIL CAMPUR', 'consumable', 1, null, null, 1, 'Consumable', 361),
    ('F', 'RA-F-040', 'SCREW MP2D', 'consumable', 1, null, null, 1, 'Consumable', 362),
    ('F', 'RA-F-041', 'SKRUP KAYU', 'consumable', 2, null, null, 2, 'Consumable', 363),
    ('F', 'RA-F-042', 'SKRUP GIPSUM', 'consumable', 1, null, null, 1, 'Consumable', 364),
    ('F', 'RA-F-043', 'SKRUP BAUT', 'consumable', 1, null, null, 1, 'Consumable', 365),
    ('F', 'RA-F-044', 'NUT M3', 'consumable', 1, null, null, 1, 'Consumable', 366),
    ('F', 'RA-F-045', 'BAUT M2', 'consumable', 1, null, null, 1, 'Consumable', 367),
    ('F', 'RA-F-046', 'JUMPER TERMINAL BLOK', 'consumable', 1, null, null, 1, 'Consumable', 368),
    ('F', 'RA-F-047', 'SKUN RING VF2-6', 'consumable', 1, null, null, 1, 'Consumable', 369),
    ('F', 'RA-F-048', 'SKUN SC70-12', 'consumable', 2, null, null, 2, 'Consumable', 370),
    ('F', 'RA-F-049', 'SKUN 50A-M8', 'consumable', 1, null, null, 1, 'Consumable', 371),
    ('F', 'RA-F-050', 'SKUN VF1.25-4BK', 'consumable', 1, null, null, 1, 'Consumable', 372),
    ('F', 'RA-F-051', 'SKUN SC6-6', 'consumable', 1, null, null, 1, 'Consumable', 373),
    ('F', 'RA-F-052', 'SKUN KECIL CAMPUR', 'consumable', 1, null, null, 1, 'Consumable', 374),
    ('F', 'RA-F-053', 'SKUN 2-8', 'consumable', 1, null, null, 1, 'Consumable', 375),
    ('F', 'RA-F-054', 'SKUN RVS-2-5', 'consumable', 1, null, null, 1, 'Consumable', 376),
    ('F', 'RA-F-055', 'DYNABOLT', 'consumable', 3, null, null, 3, 'Consumable', 377),
    ('F', 'RA-F-056', 'SKUN 95-10', 'consumable', 1, null, null, 1, 'Consumable', 378),
    ('F', 'RA-F-057', 'RING M10', 'consumable', 1, null, null, 1, 'Consumable', 379),
    ('F', 'RA-F-058', 'WL M10', 'consumable', 1, null, null, 1, 'Consumable', 380),
    ('F', 'RA-F-059', 'RING PIR M12', 'consumable', 1, null, null, 1, 'Consumable', 381),
    ('F', 'RA-F-060', 'RING PLAT', 'consumable', 3, null, null, 3, 'Consumable', 382),
    ('F', 'RA-F-061', 'VINIL V4', 'consumable', 4, null, null, 4, 'Consumable', 383),
    ('F', 'RA-F-062', 'RANTAI', 'inventory', 1, null, null, 1, 'Inventory', 384),
    ('F', 'RA-F-063', 'LED HOLDER 5MM', 'consumable', 1, null, null, 1, 'Consumable', 385),
    ('F', 'RA-F-064', 'SEKRING KACA', 'consumable', 1, null, null, 1, 'Consumable', 386),
    ('F', 'RA-F-065', 'SOKET 14PIN', 'consumable', 1, null, null, 1, 'Consumable', 387),
    ('F', 'RA-F-066', 'ENGSEL AKRILIK', 'consumable', 1, null, null, 1, 'Consumable', 388),
    ('F', 'RA-F-067', 'ENGSEL STAINLEEA1', 'consumable', 1, null, null, 1, 'Consumable', 389),
    ('F', 'RA-F-068', 'PILOT LAND', 'consumable', 1, null, null, 1, 'Consumable', 390),
    ('F', 'RA-F-069', 'KONEKTOR DB15 VGA', 'consumable', 1, null, null, 1, 'Consumable', 391),
    ('F', 'RA-F-070', 'CLAM OMEGA', 'consumable', 2, null, null, 2, 'Consumable', 392),
    ('F', 'RA-F-071', 'TIE HOLDER', 'consumable', 1, null, null, 1, 'Consumable', 393),
    ('F', 'RA-F-072', 'SET KUNCI PINTU', 'consumable', 1, null, null, 1, 'Consumable', 394),
    ('F', 'RA-F-073', 'T NUT', 'consumable', 1, null, null, 1, 'Consumable', 395),
    ('F', 'RA-F-074', 'KONEKTOR JST', 'consumable', 2, null, null, 2, 'Consumable', 396),
    ('F', 'RA-F-075', 'JACK MALE', 'consumable', 1, null, null, 1, 'Consumable', 397),
    ('F', 'RA-F-076', 'BUT TERMINAL', 'consumable', 1, null, null, 1, 'Consumable', 398),
    ('F', 'RA-F-077', 'BRACET', 'consumable', 2, null, null, 2, 'Consumable', 399),
    ('F', 'RA-F-078', 'TAMENG VSOR BRACET', 'consumable', 1, null, null, 1, 'Consumable', 400),
    ('F', 'RA-F-079', 'MOLOX SCT', 'consumable', 1, null, null, 1, 'Consumable', 401),
    ('F', 'RA-F-080', 'OMRON MICRO SENSOR', 'consumable', 1, null, null, 1, 'Consumable', 402),
    ('F', 'RA-F-081', 'KONEKTTOR CONDUIT', 'consumable', 1, null, null, 1, 'Consumable', 403),
    ('F', 'RA-F-082', 'OBENG MAGNET MINI', 'consumable', 1, null, null, 1, 'Consumable', 404),
    ('F', 'RA-F-083', 'SHEAL TAPE', 'consumable', 1, null, null, 1, 'Consumable', 405),
    ('F', 'RA-F-084', 'KLEM CLIPSAL', 'consumable', 1, null, null, 1, 'Consumable', 406),
    ('F', 'RA-F-085', 'ENGSEL TIPE DZ-400', 'consumable', 2, null, null, 2, 'Consumable', 407),
    ('F', 'RA-F-086', 'SELENOID VALVE', 'consumable', 3, null, null, 3, 'Consumable', 408),
    ('F', 'RA-F-087', 'TERMISTOR', 'consumable', 1, null, null, 1, 'Consumable', 409),
    ('F', 'RA-F-088', 'SEGEL MEKANIK', 'consumable', 1, null, null, 1, 'Consumable', 410),
    ('F', 'RA-F-089', 'PAKU BERBAGAI UKURAN', 'consumable', 1, null, null, 1, 'Consumable', 411),
    ('F', 'RA-F-090', 'PHONIX CONTACT', 'consumable', 1, null, null, 1, 'Consumable', 412),
    ('F', 'RA-F-091', 'AMPLAS', 'consumable', 1, null, null, 1, 'Consumable', 413),
    ('F', 'RA-F-092', 'BATU GRINDA POTONG UK 355', 'consumable', 2, null, null, 2, 'Consumable', 414),
    ('F', 'RA-F-093', 'SKUN Y HITAM 5,5-6MM', 'consumable', 1, null, null, 1, 'Consumable', 415),
    ('F', 'RA-F-094', 'SKUN Y SNB2-4 SL', 'consumable', 2, null, null, 2, 'Consumable', 416),
    ('F', 'RA-F-095', 'SKUN Y 55-5Y', 'consumable', 1, null, null, 1, 'Consumable', 417),
    ('F', 'RA-F-096', 'SKUN Y EMAS', 'consumable', 1, null, null, 1, 'Consumable', 418),
    ('F', 'RA-F-097', 'SKUN GEPENG PLASTIC', 'consumable', 1, null, null, 1, 'Consumable', 419),
    ('F', 'RA-F-098', 'SKUN MDD', 'consumable', 1, null, null, 1, 'Consumable', 420),
    ('F', 'RA-F-099', 'SKUN CAMPUR', 'consumable', 1, null, null, 1, 'Consumable', 421),
    ('F', 'RA-F-100', 'JP M3X15', 'consumable', 1, null, null, 1, 'Consumable', 422),
    ('F', 'RA-F-101', 'JP M5X110', 'consumable', 1, null, null, 1, 'Consumable', 423),
    ('F', 'RA-F-102', 'JP M5X10', 'consumable', 2, null, null, 2, 'Consumable', 424),
    ('F', 'RA-F-103', 'JP CAMPURAN', 'consumable', 2, null, null, 2, 'Consumable', 425),
    ('F', 'RA-F-104', 'JP M5X60', 'consumable', 1, null, null, 1, 'Consumable', 426),
    ('F', 'RA-F-105', 'JP M6', 'consumable', 2, null, null, 2, 'Consumable', 427),
    ('F', 'RA-F-106', 'JP M2', 'consumable', 5, null, null, 5, 'Consumable', 428),
    ('F', 'RA-F-107', 'JP M3', 'consumable', 6, null, null, 6, 'Consumable', 429),
    ('F', 'RA-F-108', 'KARET PELINDUNG SKUN GEPENG', 'consumable', 1, null, null, 1, 'Consumable', 430),
    ('F', 'RA-F-109', 'BL M3X10', 'consumable', 1, null, null, 1, 'Consumable', 431),
    ('F', 'RA-F-110', 'BL M5X100', 'consumable', 1, null, null, 1, 'Consumable', 432),
    ('F', 'RA-F-111', 'BL M8X25', 'consumable', 1, null, null, 1, 'Consumable', 433),
    ('F', 'RA-F-112', 'BL M10X25', 'consumable', 1, null, null, 1, 'Consumable', 434),
    ('F', 'RA-F-113', 'BL M6X75', 'consumable', 1, null, null, 1, 'Consumable', 435),
    ('F', 'RA-F-114', 'BL M12', 'consumable', 1, null, null, 1, 'Consumable', 436),
    ('F', 'RA-F-115', 'BL M10X30', 'consumable', 1, null, null, 1, 'Consumable', 437),
    ('F', 'RA-F-116', 'BL M6X60', 'consumable', 1, null, null, 1, 'Consumable', 438),
    ('F', 'RA-F-117', 'BL M5X60', 'consumable', 1, null, null, 1, 'Consumable', 439),
    ('F', 'RA-F-118', 'BL M8X30', 'consumable', 1, null, null, 1, 'Consumable', 440),
    ('F', 'RA-F-119', 'BL M5X12', 'consumable', 1, null, null, 1, 'Consumable', 441),
    ('F', 'RA-F-120', 'BL M10', 'consumable', 2, null, null, 2, 'Consumable', 442),
    ('F', 'RA-F-121', 'BL M4X12', 'consumable', 1, null, null, 1, 'Consumable', 443),
    ('F', 'RA-F-122', 'BL CAMPURAN', 'consumable', 5, null, null, 5, 'Consumable', 444),
    ('F', 'RA-F-123', 'BL M6', 'consumable', 1, null, null, 1, 'Consumable', 445),
    ('F', 'RA-F-124', 'BL M4X30', 'consumable', 1, null, null, 1, 'Consumable', 446),
    ('F', 'RA-F-125', 'Siemens 6ES7592', 'unclassified', 1, null, null, null, null, 447),
    ('G', 'RA-G-001', 'Kuas', 'inventory', 3, null, 1, 4, 'Inventory', 451),
    ('G', 'RA-G-002', 'Obeng magnet mini', 'inventory', 1, null, null, 1, 'Inventory', 452),
    ('G', 'RA-G-003', 'Linggis', 'inventory', null, null, null, null, 'Inventory', 453),
    ('G', 'RA-G-004', 'Tempat Solder', 'inventory', 2, null, null, 2, 'Inventory', 454),
    ('G', 'RA-G-005', 'Solder', 'inventory', 11, null, null, 11, 'Inventory', 455),
    ('G', 'RA-G-006', 'Skun', 'inventory', 12, null, 5, 17, 'Inventory', 456),
    ('G', 'RA-G-007', 'OBENG', 'inventory', 19, null, null, 19, 'Inventory', 457),
    ('G', 'RA-G-008', 'tespen', 'inventory', 1, null, null, 1, 'Inventory', 458),
    ('G', 'RA-G-009', 'Palu', 'inventory', 1, null, null, 1, 'Inventory', 459),
    ('G', 'RA-G-010', 'Kikir las', 'inventory', 2, null, null, 2, 'Inventory', 460),
    ('G', 'RA-G-011', 'Kunci L 1,5 MM', 'inventory', 3, null, null, 3, 'Inventory', 461),
    ('G', 'RA-G-012', 'Kunci L 4MM', 'inventory', 2, null, null, 2, 'Inventory', 462),
    ('G', 'RA-G-013', 'Kunci L 5MM', 'inventory', 15, null, null, 15, 'Inventory', 463),
    ('G', 'RA-G-014', 'Kunci L 6MM', 'inventory', 1, null, null, 1, 'Inventory', 464),
    ('G', 'RA-G-015', 'Kunci L 8MM', 'inventory', 10, null, null, 10, 'Inventory', 465),
    ('G', 'RA-G-016', 'Kunci L 10MM', 'inventory', 12, null, null, 12, 'Inventory', 466),
    ('G', 'RA-G-017', 'Kunci L 14MM', 'inventory', 1, null, null, 1, 'Inventory', 467),
    ('G', 'RA-G-018', 'Overval Stainless Steel', 'inventory', 2, null, null, 2, 'Inventory', 468),
    ('G', 'RA-G-019', 'Kunci inggris', 'inventory', 1, null, null, 1, 'Inventory', 469),
    ('G', 'RA-G-020', 'Kunci pass', 'inventory', 15, null, 2, 17, 'Inventory', 470),
    ('G', 'RA-G-021', 'Kunci ring', 'inventory', 4, null, null, 4, 'Inventory', 471),
    ('H', 'RA-H-001', 'Hydraulic Crimping Tool', 'inventory', 1, null, null, 1, 'Inventory', 472),
    ('H', 'RA-H-002', 'Manual Tube Bender', 'inventory', 1, null, null, 1, 'Inventory', 473),
    ('H', 'RA-H-003', 'Mesin Bor Rotary Hammer', 'inventory', 1, null, null, 1, 'Inventory', 474),
    ('H', 'RA-H-004', 'Mata Bor Gestar Hole Saw', 'inventory', 2, null, null, 2, 'Inventory', 475),
    ('H', 'RA-H-005', 'Tang Rivet Nut', 'inventory', 1, null, null, 1, 'Inventory', 476),
    ('H', 'RA-H-006', 'Heat Gun', 'inventory', 1, 1, null, null, 'Inventory', 477),
    ('H', 'RA-H-007', 'Mesin Bor Bosch (beton)', 'inventory', 1, null, null, 1, 'Inventory', 478),
    ('H', 'RA-H-008', 'Mata Bor STANLEY', 'inventory', 1, null, null, 1, 'Inventory', 479),
    ('H', 'RA-H-009', 'Bor listrik STANLEY', 'inventory', 1, 1, null, null, 'Inventory', 480),
    ('H', 'RA-H-010', 'BOR TANGAN CORDLESS', 'inventory', 1, 1, null, null, 'Inventory', 481),
    ('H', 'RA-H-011', 'LUCID BOR LISTRIK', 'inventory', 2, 1, null, 1, 'Inventory', 482),
    ('H', 'RA-H-012', 'BOR KENMASTER', 'inventory', 1, 1, null, null, 'Inventory', 483),
    ('H', 'RA-H-013', 'PRINTER TABEL', 'inventory', 1, 1, null, null, 'Inventory', 484),
    ('H', 'RA-H-014', 'Kotak Stop Kontak', 'unclassified', 1, null, null, null, null, 485),
    ('J', 'RA-J-001', 'LAMPU LED 100W', 'inventory', 1, null, null, 1, 'Inventory', 489),
    ('J', 'RA-J-002', 'HELM PROYEK', 'inventory', 14, 2, null, 12, 'Inventory', 490),
    ('J', 'RA-J-003', 'SARUNG TANGAN', 'consumable', 2, 2, null, null, 'Consumable', 491),
    ('J', 'RA-J-004', 'LAMPU KERJA GANTUNG 2', 'inventory', 2, null, null, 2, 'Inventory', 492),
    ('J', 'RA-J-005', 'KACAMATA SAFETY', 'inventory', 1, null, null, 1, 'Inventory', 493),
    ('J', 'RA-J-006', 'STOP KONTAK', 'inventory', 2, 2, null, 2, 'Inventory', 494),
    ('J', 'RA-J-001-2', 'BODY HARNES', 'inventory', 2, null, null, 2, 'Inventory', 495),
    ('J', 'RA-J-002-2', 'ROMPI', 'inventory', 1, null, null, 1, 'Inventory', 496),
    ('J', 'RA-J-003-2', 'TAS', 'inventory', 6, null, null, 6, 'Inventory', 497),
    ('J', 'RA-J-004-2', 'HALF MASK + FILTERS', 'inventory', 2, null, null, 2, 'Inventory', 498),
    ('J', 'RA-J-005-2', 'POLICE LANE', 'consumable', 1, null, null, 1, 'Consumable', 499),
    ('J', 'RA-J-006-2', 'EARMUF HELMET', 'inventory', 6, null, null, 6, 'Inventory', 500),
    ('J', 'RA-J-007', 'JAS HUJAN', 'consumable', 1, null, null, 1, 'Consumable', 501),
    ('J', 'RA-J-008', 'LYMAN MASTER GUNSMITH', 'consumable', 1, null, null, 1, 'Consumable', 502),
    ('J', 'RA-J-009', 'PIPA LOGAM', 'consumable', 1, null, null, 1, 'Consumable', 503),
    ('J', 'RA-J-010', 'TALI RAFIA', 'consumable', 1, 1, null, null, 'Consumable', 504),
    ('K', 'RA-K-001', 'HOLE SAW SIZE 14MM', 'inventory', 1, null, null, 1, 'Inventory', 505),
    ('K', 'RA-K-002', 'HOLE SAW SIZE 17MM', 'inventory', 1, null, null, 1, 'Inventory', 506),
    ('K', 'RA-K-003', 'METAL HOLE SAW SIZE 22MM', 'inventory', 1, null, null, 1, 'Inventory', 507),
    ('K', 'RA-K-004', 'HOLE SAW SIZE 24MM', 'inventory', 1, null, null, 1, 'Inventory', 508),
    ('K', 'RA-K-005', 'HOLE SAW SIZE 29MM', 'inventory', 1, null, null, 1, 'Inventory', 509),
    ('K', 'RA-K-006', 'HOLE SAW SIZE 38MM', 'inventory', 1, null, null, 1, 'Inventory', 510),
    ('K', 'RA-K-007', 'HOLE SAW SIZE 41MM', 'inventory', 1, null, null, 1, 'Inventory', 511),
    ('K', 'RA-K-008', 'HOLE SAW SIZE 42MM', 'inventory', 1, null, null, 1, 'Inventory', 512),
    ('K', 'RA-K-009', 'HOLE SAW SIZE 45MM', 'inventory', 1, null, null, 1, 'Inventory', 513),
    ('K', 'RA-K-010', 'HOLE SAW SIZE 48MM', 'inventory', 1, null, null, 1, 'Inventory', 514),
    ('K', 'RA-K-011', 'HOLE SAW TCT 80MM', 'inventory', 4, null, null, 4, 'Inventory', 515),
    ('K', 'RA-K-012', 'HOLE CUTTER TCT 22MM', 'inventory', 1, null, null, 1, 'Inventory', 516),
    ('K', 'RA-K-013', 'HOLE CUTTER TCT 28MM', 'inventory', 1, null, null, 1, 'Inventory', 517),
    ('K', 'RA-K-014', 'HOLE CUTTER TCT 30MM', 'inventory', 1, null, null, 1, 'Inventory', 518),
    ('K', 'RA-K-017', 'HOLE CUTTER HSS 55MM', 'inventory', 1, null, null, 1, 'Inventory', 519),
    ('K', 'RA-K-018', 'HOLE CUTTER TCT 60MM', 'inventory', 1, null, null, 1, 'Inventory', 520),
    ('K', 'RA-K-019', 'HAND TAPS 1/4-19', 'inventory', 2, null, null, 2, 'Inventory', 521),
    ('K', 'RA-K-020', 'HAND TAPS 1/4-20', 'inventory', 2, null, null, 2, 'Inventory', 522),
    ('K', 'RA-K-021', 'HAND TAPS 1/8-28', 'inventory', 1, null, null, 1, 'Inventory', 523),
    ('K', 'RA-K-022', 'HAND TAPS 3/8-19', 'inventory', 1, null, null, 1, 'Inventory', 524),
    ('K', 'RA-K-023', 'HAND TAPS 7/16-14', 'inventory', 1, null, null, 1, 'Inventory', 525),
    ('K', 'RA-K-024', 'HAND TAPS M6X1.0', 'inventory', 1, null, null, 1, 'Inventory', 526),
    ('K', 'RA-K-025', 'HAND TAPS M8X1.25', 'inventory', 3, null, null, 3, 'Inventory', 527),
    ('K', 'RA-K-026', 'HAND TAPS M12X1.75', 'inventory', 2, null, null, 2, 'Inventory', 528),
    ('K', 'RA-K-027', 'HAND TAPS M14X2.0', 'inventory', 1, null, null, 1, 'Inventory', 529),
    ('K', 'RA-K-028', 'MATA BOR YAMAHA HTP2M8X1', 'inventory', 3, null, null, 3, 'Inventory', 530),
    ('K', 'RA-K-029', 'LABEL AUTO MANUAL', 'consumable', 1, null, null, 1, 'Consumable', 531),
    ('K', 'RA-K-030', 'LABEL STOP', 'consumable', 1, null, null, 1, 'Consumable', 532),
    ('K', 'RA-K-031', 'LABEL RUN', 'consumable', 1, null, null, 1, 'Consumable', 533),
    ('K', 'RA-K-032', 'LABEL START', 'consumable', 1, null, null, 1, 'Consumable', 534),
    ('K', 'RA-K-033', 'LABEL CNV6 REVERSE', 'consumable', 1, null, null, 1, 'Consumable', 535),
    ('K', 'RA-K-034', 'LABEL TRIP', 'consumable', 1, null, null, 1, 'Consumable', 536),
    ('K', 'RA-K-035', 'LABEL CNV7 FORWARD', 'consumable', 1, null, null, 1, 'Consumable', 537),
    ('K', 'RA-K-036', 'LABEL R1', 'consumable', 1, null, null, 1, 'Consumable', 538),
    ('K', 'RA-K-037', 'LABEL S', 'consumable', 1, null, null, 1, 'Consumable', 539),
    ('K', 'RA-K-038', 'LABEL R.O SYSTEM NEW OFF OLD', 'consumable', 1, null, null, 1, 'Consumable', 540),
    ('K', 'RA-K-039', 'CHAIN BLOK', 'inventory', 1, null, null, 1, 'Inventory', 541),
    ('K', 'RA-K-040', 'MATA BOR BETON SDS 14X280P', 'inventory', 1, null, null, 1, 'Inventory', 542),
    ('K', 'RA-K-041', 'MATA BOR BETON SDS 14X280F', 'inventory', 1, null, null, 1, 'Inventory', 543),
    ('K', 'RA-K-042', 'METAL PUSS BUTTOMN', 'inventory', 1, null, null, 1, 'Inventory', 544),
    ('K', 'RA-K-043', 'CABLE GLAND PUTIH BESAR', 'consumable', 6, null, null, 6, 'Consumable', 545),
    ('K', 'RA-K-044', 'CABLE GLAND KECIL', 'consumable', 9, null, null, 9, 'Consumable', 546),
    ('K', 'RA-K-045', 'EMT CONDUIT CONEKTOR BESAR', 'consumable', 8, null, null, 8, 'Consumable', 547),
    ('K', 'RA-K-046', 'EMT CONDUIT CONEKTOR KECIL', 'consumable', 6, null, null, 6, 'Consumable', 548),
    ('K', 'RA-K-047', 'KABLE KAWAT BAJA', 'consumable', 1, null, null, 1, 'Consumable', 549),
    ('K', 'RA-K-048', 'MATA BOR DAN DOWEL', 'inventory', 1, null, null, 1, 'Inventory', 550),
    ('K', 'RA-K-049', 'PLASTIC PARCEL POLOS', 'inventory', 1, null, null, 1, 'Inventory', 551),
    ('K', 'RA-K-050', 'MITSUBHISI FXT3G-24M', 'inventory', 1, null, null, 1, 'Inventory', 552),
    ('K', 'RA-K-051', 'MATA BOR BESI', 'inventory', 1, null, null, 1, 'Inventory', 553),
    ('K', 'RA-K-052', 'MATA BOR BESI 5.5MM', 'inventory', 1, null, null, 1, 'Inventory', 554),
    ('K', 'RA-K-053', 'FITTING 1 SET', 'consumable', 1, null, null, 1, 'Consumable', 555),
    ('K', 'RA-K-054', 'MATA BOR CAMPURAN', 'inventory', 1, null, null, 1, 'Inventory', 556),
    ('K', 'RA-K-055', 'STAND HAND', 'inventory', 3, null, null, 3, 'Inventory', 557),
    ('K', 'RA-K-056', 'PILOT LAMP', 'consumable', 5, 3, null, 2, 'Consumable', 558),
    ('K', 'RA-K-057', 'HEADER CAMPURAN', 'consumable', 1, null, null, 1, 'Consumable', 559),
    ('K', 'RA-K-058', 'DIODA BIASA', 'consumable', 3, 1, null, 2, 'Consumable', 560),
    ('K', 'RA-K-059', 'DIODA ZIENER', 'consumable', 1, null, null, 1, 'Consumable', 561),
    ('K', 'RA-K-060', 'FUSE LISTRIK', 'consumable', 1, null, null, 1, 'Consumable', 562),
    ('K', 'RA-K-061', 'IC ATMEGA8A-PU', 'consumable', 1, null, null, 1, 'Consumable', 563),
    ('K', 'RA-K-062', 'IC HCF40', 'consumable', 1, null, null, 1, 'Consumable', 564),
    ('K', 'RA-K-063', 'BAUT CAMPURAN', 'consumable', 2, null, null, 2, 'Consumable', 565),
    ('K', 'RA-K-064', 'LABEL LEVEL HOLDER', 'consumable', 1, null, null, 1, 'Consumable', 566),
    ('K', 'RA-K-065', 'KUNCI L 1MM', 'consumable', 1, null, null, 1, 'Consumable', 567),
    ('K', 'RA-K-066', 'RESISTOR 47K', 'consumable', 1, null, null, 1, 'Consumable', 568),
    ('K', 'RA-K-067', 'KUNCI CAMPURAN', 'inventory', 1, null, null, 1, 'Inventory', 569),
    ('K', 'RA-K-068', 'RESISTOR CAMPURAN', 'consumable', 1, null, null, 1, 'Consumable', 570),
    ('K', 'RA-K-069', 'RESISTOR 22K', 'consumable', 1, null, null, 1, 'Consumable', 571),
    ('K', 'RA-K-070', 'KAPASITOR 1000uf ELEKTROLIT', 'consumable', 2, null, null, 2, 'Consumable', 572),
    ('K', 'RA-K-071', 'KAPASITOR 2200uF ELEKTROLIT', 'consumable', 1, null, null, 1, 'Consumable', 573),
    ('K', 'RA-K-072', 'SERVO COUPLING', 'consumable', 1, null, null, 1, 'Consumable', 574),
    ('K', 'RA-K-073', 'KAPASITOR 39NF KERAMIK', 'consumable', 1, null, null, 1, 'Consumable', 575),
    ('K', 'RA-K-074', 'RAM MEMORY', 'consumable', 1, null, null, 1, 'Consumable', 576),
    ('K', 'RA-K-075', 'JACK CONNECTOR SOCKET', 'consumable', 1, null, null, 1, 'Consumable', 577),
    ('K', 'RA-K-076', 'PAPAN ARUS DAN AMPLIVOLTAGE', 'consumable', 1, null, null, 1, 'Consumable', 578),
    ('K', 'RA-K-077', 'KAPASITOR 100NF KERAMIK', 'unclassified', 1, null, null, null, null, 579),
    ('T', 'RA-T-001', 'HELM PROYEK BARU', 'inventory', 6, null, null, 6, 'INVENTARIS', 583),
    ('T', 'RA-T-002', 'KERTAS HVS A4', 'consumable', 1, null, null, 1, 'CONSUMABLE', 584),
    ('T', 'RA-T-003', 'ROMPI PROYEK', 'inventory', 12, null, null, 12, 'INVENTARIS', 585),
    ('T', 'RA-T-004', 'ROMPI FUTSAL', 'inventory', 6, null, null, 6, 'INVENTARIS', 586),
    ('T', 'RA-T-005', 'KERTAS NOTA', 'consumable', 1, null, null, 1, 'CONSUMABLE', 587),
    ('T', 'RA-T-006', 'KERTAS STIKER A4', 'consumable', 2, null, null, 2, 'CONSUMABLE', 588),
    ('T', 'RA-T-007', 'BAJU SAFETY', 'inventory', 2, null, null, 2, 'INVENTARIS', 589),
    ('T', 'RA-T-008', 'KERTAS AMPLOP', 'consumable', 1, null, null, 1, 'CONSUMABLE', 590),
    ('T', 'RA-T-009', 'PLASTIC HANDEL', 'consumable', 1, null, null, 1, 'CONSUMABLE', 591),
    ('T', 'RA-T-010', 'PENJEPITHELMPROYEK', 'inventory', 1, null, null, 1, 'INVENTARIS', 592),
    ('T', 'RA-T-011', 'ASESORI HELM', 'inventory', 11, null, null, 11, 'INVENTARIS', 593),
    ('U', 'RA-U-001', 'PRINTER', 'inventory', 1, null, null, 1, 'INVENTARIS', 594),
    ('U', 'RA-U-002', 'SIGNAL GENERATOR', 'inventory', 1, null, null, 1, 'INVENTARIS', 595),
    ('U', 'RA-U-003', 'PENGHAPUS PAPAN TULIS', 'inventory', 1, null, null, 1, 'INVENTARIS', 596),
    ('U', 'RA-U-004', 'PENGUKUR GETARAN DIGITAL', 'inventory', 1, null, null, 1, 'INVENTARIS', 597),
    ('U', 'RA-U-005', 'BARCODE SCANER', 'inventory', 1, null, null, 1, 'INVENTARIS', 598),
    ('U', 'RA-U-006', 'JANGKA SORONG DIGITAL', 'inventory', 1, null, null, 1, 'INVENTARIS', 599),
    ('U', 'RA-U-007', 'CAMERA CANON', 'inventory', 1, null, null, 1, 'INVENTARIS', 600),
    ('U', 'RA-U-008', 'SMART SENSOR', 'inventory', 1, null, null, 1, 'INVENTARIS', 601),
    ('U', 'RA-U-009', 'INVENTER MITSUBISHI', 'inventory', 1, null, null, 1, 'INVENTARIS', 602),
    ('U', 'RA-U-010', 'AVO DIGITAL', 'inventory', 1, null, null, 1, 'INVENTARIS', 603),
    ('U', 'RA-U-011', 'TACO METTER GENGGAM', 'inventory', 1, null, null, 1, 'INVENTARIS', 604),
    ('U', 'RA-U-012', 'OPTICAL POWER METER', 'inventory', 1, null, null, 1, 'INVENTARIS', 605),
    ('U', 'RA-U-013', 'LASER DISTANCE METER', 'inventory', 2, null, null, 2, 'INVENTARIS', 606),
    ('U', 'RA-U-014', 'FAST CONNECTOR FIBER OPTIK', 'inventory', 3, null, null, 3, 'INVENTARIS', 607),
    ('U', 'RA-U-015', 'FIBER CLENVER FC-6S', 'inventory', 1, null, null, 1, 'INVENTARIS', 608),
    ('U', 'RA-U-016', 'CONNECTOR DB25 MALE', 'inventory', 2, null, null, 2, 'INVENTARIS', 609),
    ('U', 'RA-U-017', 'PROGRAMMABLE CONTROLLER', 'inventory', 1, null, null, 1, 'INVENTARIS', 610),
    ('U', 'RA-U-018', 'FIBER OPTIC SRIPPER', 'inventory', 1, null, null, 1, 'INVENTARIS', 611),
    ('U', 'RA-U-019', 'VISUAL FAULT LOCATOR', 'inventory', 1, null, null, 1, 'INVENTARIS', 612),
    ('U', 'RA-U-020', 'THERMAL PRINTER', 'inventory', 1, null, null, 1, 'INVENTARIS', 613),
    ('U', 'RA-U-021', 'PROYEKTOR', 'unclassified', 1, null, null, null, null, 614)
)
insert into public.inventory_items (
  rack_id, code, name, item_type, initial_quantity, used_quantity,
  added_quantity, current_quantity, source_note, source_row
)
select
  rack_targets.id, inventory_seed.code, inventory_seed.name, inventory_seed.item_type,
  inventory_seed.initial_quantity, inventory_seed.used_quantity, inventory_seed.added_quantity,
  inventory_seed.current_quantity, inventory_seed.source_note, inventory_seed.source_row
from inventory_seed
join public.racks as rack_targets
  on rack_targets.code = inventory_seed.rack_code
join public.locations as locations
  on locations.id = rack_targets.location_id
  and locations.code = 'MAIN-WH'
on conflict (rack_id, code) do update
set
  name = excluded.name,
  item_type = excluded.item_type,
  initial_quantity = excluded.initial_quantity,
  used_quantity = excluded.used_quantity,
  added_quantity = excluded.added_quantity,
  current_quantity = excluded.current_quantity,
  source_note = excluded.source_note,
  source_row = excluded.source_row;
